name: ci

on:
  pull_request:

jobs:

  debian-10-11:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: ['debian10-amd64-sse2', 'debian11-amd64-sse2',
             'debian10-i386-sse2', 'debian11-i386-sse2',
             'debian10-arm64-asimd', 'debian11-arm64-asimd',
             'debian10-armhf-neon', 'debian11-armhf-neon',
             'debian10-ppc64el-vmx', 'debian11-ppc64el-vmx',
             'raspios11-arm64',
             'raspios11-armhf']
    runs-on: [ self-hosted, "${{matrix.os}}" ]
    name: ${{matrix.os}}
    steps:
      - name: Clean
        run: rm -rf *
      - name: Clone sin-python
        uses: actions/checkout@v3
      - name: Python version
        run: python3 --version
      - name: Tests
        run: pytest-3 tests/*.py

  unix:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: ['debian12-amd64-sse2', 'debian13-amd64-sse2',
             'debian12-i386-sse2', 'debian13-i386-sse2',
             'debian12-arm64-asimd', 'debian13-arm64-asimd',
             'debian12-armhf-neon', 'debian13-armhf-neon',
             'debian12-ppc64el-vmx', 'debian13-ppc64el-vmx',
             'raspios12-arm64',
             'raspios12-armhf-cpu',
             'macos13-amd64-avx2', 'macos14-amd64-avx2',
             'macos14-arm64-asimd', 'macos14-arm64-asimd']
    runs-on: [ self-hosted, "${{matrix.os}}" ]
    name: ${{matrix.os}}
    steps:
      - name: Clean
        run: rm -rf *
      - name: Clone sin-python
        uses: actions/checkout@v3
      - name: Python version
        run: python3 --version
      - name: Tests
        run: pytest tests/*.py
